### ISSUE TITLE
Errors in examples

### ISSUE THREAD

**Issue by tomhajjar** [tvrusso/Xyce_qucs-s_Examples#1]
I found a few errors in 03-CommonEmitter_flat and 04-CommonEmitter_subcircuited folders. The primary error was R1 is 39K when it should be 39k. After fixing the typo, plots were blank so I had to delete and recreate the plots. I cleaned up the schematics and graphics as well.

[Examples_xyce.zip](https://github.com/tvrusso/Xyce_qucs-s_Examples/files/9316642/Examples_xyce.zip)

**Comment by tvrusso** [comment]
I was certain I had commented this before, but somehow my comments are lost.

There is absolutely no difference in Xyce between "39k" and "39K" --- Xyce's netlist parser is case-insensitive.

So there is no typo to fix, and no error.

When I run either of the examples you say need fixing, they work just fine unmodified.

![03_CommonEmitter_flat](https://user-images.githubusercontent.com/10872812/184424699-01b1a493-9233-46cc-9dbe-57471abeb756.png)

![04CommonEmitter_Driver](https://user-images.githubusercontent.com/10872812/184424728-19d0b421-db34-432e-b2bb-ea223a739440.png)

I have closed this issue as invalid.

**Comment by tomhajjar** [comment]
I still cannot reproduce your data. The two plots are blank. For whatever reason auto scaling doesn't work. If I set the limits manually I can get a trace. 

Lastly with Vcc = 1 Volt, the NPN is starved for bias. If I make it 10 volts things look a bit better. 

![2022-08-12_153016](https://user-images.githubusercontent.com/102838604/184430544-9f067fb7-999f-4be7-ad0a-f2eebe81347c.jpg)
![2022-08-12_153157](https://user-images.githubusercontent.com/102838604/184430561-4f309e7b-c24d-488f-9474-01bce32a5c36.jpg)

**Comment by tvrusso** [comment]
The only mistake here is in the VCC device, which was incorrectly set to the default value of the device when placed into the Qucs-s schematic.  It should have been 12 volts, which is what it was in the original article from which it was taken and the Xyce App note (on the Xyce web site's documentation and tutorials page) for how to use Xyce with gEDA.

When correctly set to 12V for vcc, the plots look correct.  I cannot account for why my charts autoranged correctly when the VCC setting was wrong, but that's not a Xyce bug, nor is it an error in this circuit.

The common emitter circuits in Xyce_qucs-s_Examples exists primarily as a demonstration of how to do subcircuiting using qucs-s and Xyce, and the flattened version is provided only to demonstrate that the subcircuited and flat versions are the same.  The actual data output was not the point of the example, though it is nice for it to match the article from which the circuit was taken.

As such, it served its purpose even when vcc was set wrong.  But it should have been 12 volts and I have fixed it in commit 3d57578.

**Comment by tomhajjar** [comment]
Here is my changes to your work. Mostly cosmetic.

 I think Qucs-S plot auto scaling is not working for xyce . I'm using Qucs-S for Windows. If you are using Linux, maybe you don't have an issue. 

[Amplifiers_xyce.zip](https://github.com/tvrusso/Xyce_qucs-s_Examples/files/9329941/Amplifiers_xyce.zip)
